In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("german_credit_data.csv",encoding='latin-1')

In [8]:
df.head()

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little   
1           1   22  female    2     own          little         moderate   
2           2   49    male    1     own          little              NaN   
3           3   45    male    2    free          little           little   
4           4   53    male    2    free          little           little   

   Credit amount  Duration              Purpose  
0           1169         6             radio/TV  
1           5951        48             radio/TV  
2           2096        12            education  
3           7882        42  furniture/equipment  
4           4870        24                  car

In [9]:
df["PURPOSE"]=df["Purpose"].str.find('education')

In [10]:
df.head()

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little   
1           1   22  female    2     own          little         moderate   
2           2   49    male    1     own          little              NaN   
3           3   45    male    2    free          little           little   
4           4   53    male    2    free          little           little   

   Credit amount  Duration              Purpose  PURPOSE  
0           1169         6             radio/TV       -1  
1           5951        48             radio/TV       -1  
2           2096        12            education        0  
3           7882        42  furniture/equipment       -1  
4           4870        24                  car       -1

In [11]:
df["PURPOSE"]

0     -1
1     -1
2      0
3     -1
4     -1
      ..
995   -1
996   -1
997   -1
998   -1
999   -1
Name: PURPOSE, Length: 1000, dtype: int64

In [13]:
x = df.pop("PURPOSE")

In [14]:
df

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0             0   67    male    2     own             NaN           little   
1             1   22  female    2     own          little         moderate   
2             2   49    male    1     own          little              NaN   
3             3   45    male    2    free          little           little   
4             4   53    male    2    free          little           little   
..          ...  ...     ...  ...     ...             ...              ...   
995         995   31  female    1     own          little              NaN   
996         996   40    male    3     own          little           little   
997         997   38    male    2     own          little              NaN   
998         998   23    male    2    free          little           little   
999         999   27    male    2     own        moderate         moderate   

     Credit amount  Duration              Purpose  
0             1169         6             radio/TV  
1             5951        48             radio/TV  
2             2096        12            education  
3             7882        42  furniture/equipment  
4             4870        24                  car  
..             ...       ...                  ...  
995           1736        12  furniture/equipment  
996           3857        30                  car  
997            804        12             radio/TV  
998           1845        45             radio/TV  
999           4576        45                  car  

[1000 rows x 10 columns]

In [15]:
x.head(10)

0   -1
1   -1
2    0
3   -1
4   -1
5    0
6   -1
7   -1
8   -1
9   -1
Name: PURPOSE, dtype: int64

In [16]:
x=x.replace(to_replace=-1, value=0)

In [17]:
x.head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: PURPOSE, dtype: int64

In [18]:
df

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0             0   67    male    2     own             NaN           little   
1             1   22  female    2     own          little         moderate   
2             2   49    male    1     own          little              NaN   
3             3   45    male    2    free          little           little   
4             4   53    male    2    free          little           little   
..          ...  ...     ...  ...     ...             ...              ...   
995         995   31  female    1     own          little              NaN   
996         996   40    male    3     own          little           little   
997         997   38    male    2     own          little              NaN   
998         998   23    male    2    free          little           little   
999         999   27    male    2     own        moderate         moderate   

     Credit amount  Duration              Purpose  
0             1169         6             radio/TV  
1             5951        48             radio/TV  
2             2096        12            education  
3             7882        42  furniture/equipment  
4             4870        24                  car  
..             ...       ...                  ...  
995           1736        12  furniture/equipment  
996           3857        30                  car  
997            804        12             radio/TV  
998           1845        45             radio/TV  
999           4576        45                  car  

[1000 rows x 10 columns]

In [19]:
df["Age"].unique()

array([67, 22, 49, 45, 53, 35, 61, 28, 25, 24, 60, 32, 44, 31, 48, 26, 36,
       39, 42, 34, 63, 27, 30, 57, 33, 37, 58, 23, 29, 52, 50, 46, 51, 41,
       40, 66, 47, 56, 54, 20, 21, 38, 70, 65, 74, 68, 43, 55, 64, 75, 19,
       62, 59], dtype=int64)

In [20]:
df["Sex"].unique()

array(['male', 'female'], dtype=object)

In [21]:
df["Purpose"].unique()

array(['radio/TV', 'education', 'furniture/equipment', 'car', 'business',
       'domestic appliances', 'repairs', 'vacation/others'], dtype=object)

In [22]:
df["HOUSING"]=df["Housing"].str.find("free")

In [23]:
df.head()

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0           0   67    male    2     own             NaN           little   
1           1   22  female    2     own          little         moderate   
2           2   49    male    1     own          little              NaN   
3           3   45    male    2    free          little           little   
4           4   53    male    2    free          little           little   

   Credit amount  Duration              Purpose  HOUSING  
0           1169         6             radio/TV       -1  
1           5951        48             radio/TV       -1  
2           2096        12            education       -1  
3           7882        42  furniture/equipment        0  
4           4870        24                  car        0

In [24]:
df.head(100)

Unnamed: 0  Age     Sex  Job Housing Saving accounts Checking account  \
0            0   67    male    2     own             NaN           little   
1            1   22  female    2     own          little         moderate   
2            2   49    male    1     own          little              NaN   
3            3   45    male    2    free          little           little   
4            4   53    male    2    free          little           little   
..         ...  ...     ...  ...     ...             ...              ...   
95          95   58    male    2    rent          little         moderate   
96          96   61  female    2     own             NaN              NaN   
97          97   34    male    2     own        moderate         moderate   
98          98   36    male    2     own          little         moderate   
99          99   36    male    3    rent             NaN         moderate   

    Credit amount  Duration              Purpose  HOUSING  
0            1169         6             radio/TV       -1  
1            5951        48             radio/TV       -1  
2            2096        12            education       -1  
3            7882        42  furniture/equipment        0  
4            4870        24                  car        0  
..            ...       ...                  ...      ...  
95          15945        54             business       -1  
96           2012        12            education       -1  
97           2622        18             business       -1  
98           2337        36             radio/TV       -1  
99           7057        20                  car       -1  

[100 rows x 11 columns]

In [25]:
housing=df.pop("HOUSING")

In [26]:
housing.head(10)

0   -1
1   -1
2   -1
3    0
4    0
5    0
6   -1
7   -1
8   -1
9   -1
Name: HOUSING, dtype: int64

In [27]:
housing=housing.replace(to_replace=-1, value=0,)
housing=housing.replace(to_replace=0, value=9,)
housing.head(10)

0    9
1    9
2    9
3    9
4    9
5    9
6    9
7    9
8    9
9    9
Name: HOUSING, dtype: int64

In [29]:
Purpose=pd.get_dummies(df["Purpose"])
Purpose.head()

business  car  domestic appliances  education  furniture/equipment  \
0         0    0                    0          0                    0   
1         0    0                    0          0                    0   
2         0    0                    0          1                    0   
3         0    0                    0          0                    1   
4         0    1                    0          0                    0   

   radio/TV  repairs  vacation/others  
0         1        0                0  
1         1        0                0  
2         0        0                0  
3         0        0                0  
4         0        0                0

In [30]:
df["Job"].unique()

array([2, 1, 3, 0], dtype=int64)

In [31]:
df["Duration"].unique()

array([ 6, 48, 12, 42, 24, 36, 30, 15,  9, 10,  7, 60, 18, 45, 11, 27,  8,
       54, 20, 14, 33, 21, 16,  4, 47, 13, 22, 39, 28,  5, 26, 72, 40],
      dtype=int64)