In [1]:
import numpy as np
import pandas as pd

In [2]:
arr=np.array([1,2,3,4,5,6,7])
series_1=pd.Series(arr)
print(series_1)
print(type(series_1))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32
<class 'pandas.core.series.Series'>


In [3]:
arr=np.array(["a","b","c","d","e"])
s_1=pd.Series(arr,index=[11,12,13,14,15])
s_1

11    a
12    b
13    c
14    d
15    e
dtype: object

In [5]:
my_dict={
    "name":["a","b","c","d"],
    "scores":[65,451,155,21]
}

my_series=pd.Series(my_dict)
my_series

name            [a, b, c, d]
scores    [65, 451, 155, 21]
dtype: object

In [6]:
name=["a","b","c","d"]
scores=[65,451,155,21]
s=pd.Series(scores,index=name)
print(s)

a     65
b    451
c    155
d     21
dtype: int64


In [7]:
s=pd.Series(["apple","mango","banana","Grapes","kivi","pinaple"])
print(s)
print(s[1])
print(s[3])
print(s[1:])

0      apple
1      mango
2     banana
3     Grapes
4       kivi
5    pinaple
dtype: object
mango
Grapes
1      mango
2     banana
3     Grapes
4       kivi
5    pinaple
dtype: object


In [8]:
name=["a","b","c","d"]
scores=[65,451,155,21]
s=pd.Series(scores,index=name)
print(s)
print("____________________________________")
print(s.index)#to get the index
print(s.values)#to get the values
print("_______________")
#Aceesing items
print("scores of a=",s["a"])
print("scores of b=",s["b"])

a     65
b    451
c    155
d     21
dtype: int64
____________________________________
Index(['a', 'b', 'c', 'd'], dtype='object')
[ 65 451 155  21]
_______________
scores of a= 65
scores of b= 451


In [9]:
names=["a","b","c","d","f"]
scores=[120,165,151,123,154]
dict_1={
    "names":names,
    "scores":scores
}
print("Dictionary =",dict_1)
print("_______________________")
dataFrame=pd.DataFrame(dict_1)
dataFrame

Dictionary = {'names': ['a', 'b', 'c', 'd', 'f'], 'scores': [120, 165, 151, 123, 154]}
_______________________


names  scores
0     a     120
1     b     165
2     c     151
3     d     123
4     f     154

In [10]:
x=["Tata","ford","KIa","tesla","Maruthi","mahendra"]
y=[14,55,11,45,55,11]

dicti={
    0:x,
    1:y
}
df=pd.DataFrame(dicti, index=["c1","c2","c3","c4","c5","c6"],columns=["company","sales"])
df["company"]=x
df["sales"]=y

year=["2001","2022","2015","2016","2019","2020"]
empty=np.arange(0,6)
df["Year"]=year
df["empty"]=empty
df

del df["empty"]
df

company  sales  Year
c1      Tata     14  2001
c2      ford     55  2022
c3       KIa     11  2015
c4     tesla     45  2016
c5   Maruthi     55  2019
c6  mahendra     11  2020

In [11]:
random=np.random.randint(low=0, high=100, size=20)
name=np.random.choice(["a","b","c","d"],size=20)
choice=np.random.choice([10,11,12,13,14,15],size=20)
print(random)
print(name)
print(choice)

[35 15 52  8 12  9 75 73 93 29 55 29 57 13  6 91 52 75 30 80]
['c' 'b' 'd' 'b' 'b' 'd' 'a' 'c' 'c' 'c' 'c' 'c' 'b' 'd' 'd' 'a' 'c' 'c'
 'c' 'd']
[11 11 10 10 10 11 13 15 15 12 11 13 11 15 14 12 15 12 10 10]


In [12]:
data=pd.DataFrame()
data["Random"]=random
data["name"]=name
data["choice"]=choice
data

Random name  choice
0       35    c      11
1       15    b      11
2       52    d      10
3        8    b      10
4       12    b      10
5        9    d      11
6       75    a      13
7       73    c      15
8       93    c      15
9       29    c      12
10      55    c      11
11      29    c      13
12      57    b      11
13      13    d      15
14       6    d      14
15      91    a      12
16      52    c      15
17      75    c      12
18      30    c      10
19      80    d      10

In [13]:
print("shape of dataframe",data.shape)
print("column names",data.columns)
print("column values",data.values)

shape of dataframe (20, 3)
column names Index(['Random', 'name', 'choice'], dtype='object')
column values [[35 'c' 11]
 [15 'b' 11]
 [52 'd' 10]
 [8 'b' 10]
 [12 'b' 10]
 [9 'd' 11]
 [75 'a' 13]
 [73 'c' 15]
 [93 'c' 15]
 [29 'c' 12]
 [55 'c' 11]
 [29 'c' 13]
 [57 'b' 11]
 [13 'd' 15]
 [6 'd' 14]
 [91 'a' 12]
 [52 'c' 15]
 [75 'c' 12]
 [30 'c' 10]
 [80 'd' 10]]


In [14]:
data.head()

Random name  choice
0      35    c      11
1      15    b      11
2      52    d      10
3       8    b      10
4      12    b      10

In [15]:
data.tail()

Random name  choice
15      91    a      12
16      52    c      15
17      75    c      12
18      30    c      10
19      80    d      10

In [16]:
data.head(10)

Random name  choice
0      35    c      11
1      15    b      11
2      52    d      10
3       8    b      10
4      12    b      10
5       9    d      11
6      75    a      13
7      73    c      15
8      93    c      15
9      29    c      12

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Random  20 non-null     int32 
 1   name    20 non-null     object
 2   choice  20 non-null     int32 
dtypes: int32(2), object(1)
memory usage: 448.0+ bytes


In [18]:
data.describe()

Random     choice
count  20.000000  20.000000
mean   44.450000  12.050000
std    29.558995   1.877148
min     6.000000  10.000000
25%    14.500000  10.750000
50%    43.500000  11.500000
75%    73.500000  13.250000
max    93.000000  15.000000

In [19]:
data["Random"].describe()

count    20.000000
mean     44.450000
std      29.558995
min       6.000000
25%      14.500000
50%      43.500000
75%      73.500000
max      93.000000
Name: Random, dtype: float64