In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5,6,7,8,9,0])
print(array)
type(array)
array.shape

[1 2 3 4 5 6 7 8 9 0]


(10,)

In [3]:
array=np.array((1, 2, 3, 4, 5))
print(array)
type(array)
array.shape

[1 2 3 4 5]


(5,)

In [4]:
#2-D Array
array=np.array([[1,2,3],[4,5,6]])
print(array)
print(type(array))
print(array.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [5]:
#3-D Array
array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(array)
print(type(array))
print(array.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(2, 2, 3)


In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print('Number of dimensions of array a:',a.ndim,a.dtype)
print('Number of dimensions of array b:',b.ndim,b.dtype)
print('Number of dimensions of array c:',c.ndim,c.dtype)
print('Number of dimensions of array d:',d.ndim,d.dtype)

Number of dimensions of array a: 0 int32
Number of dimensions of array b: 1 int32
Number of dimensions of array c: 2 int32
Number of dimensions of array d: 3 int32


In [7]:
array = np.array([1, 2, 3, 4, 5])
print(array[0])
print(array[1])
print(array[3])
print(array[0]+array[1])

1
2
4
3


In [9]:
array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(array)
print("2nd element in first row",array[0][2])
print("4th element in second row",array[1][3])
print('5th element on 2nd row: ', array[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element in first row 3
4th element in second row 9
5th element on 2nd row:  10


In [13]:
array = np.array([["a","b","c","d","e"], [6,7,8,9,10]])
print(array[1,2])
print(array[0,1:4])
print(array[0][0:4])
print(array[0][0:4:2])
array = np.array([["a","b","c","d","e"], [6,7,8,9,10]])
print(array[0:2,2])

8
['b' 'c' 'd']
['a' 'b' 'c' 'd']
['a' 'c']
['c' '8']


In [14]:
array = np.array([1, 2, 3, 4, 5, 6, 7])
print(array[::2])

[1 3 5 7]


In [15]:
array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(array[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [16]:
array=np.array(["a","b","c","d","e"])
array1=np.array([1,2,3,4,5,6])
print(array.dtype)
print(array1.dtype)

<U1
int32


In [17]:
array1=np.array([1.0,2.3,3.5,4.4,5.9,6.6,7.3], dtype=int)
print(array1)
array2=np.array(["1","2","3","4","5"])
array2=array2.astype(int)
print(array2)

[1 2 3 4 5 6 7]
[1 2 3 4 5]


In [18]:
arr = np.array([1, 0, 3])
new_arr=arr.astype(bool)
new_arr

array([ True, False,  True])

In [19]:
arr1=np.array([1,"pranjal",3.6,"priya",10,True])
arr2=np.copy(arr1)
arr1[2]="revati"
print("Original array -",arr1)
print("Copy of original array",arr2)

Original array - ['1' 'pranjal' 'revati' 'priya' '10' 'True']
Copy of original array ['1' 'pranjal' '3.6' 'priya' '10' 'True']


In [20]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [21]:
array=np.array([[1,2,3,4,5],[11,12,13,14,15],[45,50,55,60,65]])
array.shape

(3, 5)

In [22]:
arr1=np.array([1,2,3,4,5],ndmin=3)
print(arr1)
print(arr1.shape)

[[[1 2 3 4 5]]]
(1, 1, 5)


In [23]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)
arr2=arr.reshape(4,3)
print(arr2)
print("Reshape of array",arr2.shape)

(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshape of array (4, 3)


In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1=arr.reshape(2,2,3)
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])