In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5])
for x in array:
    print(x)

1
2
3
4
5


In [4]:
array=np.array([[1,2,3,4,5],[6,7,8,9,0]],dtype=object)
for x in array:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
0


In [5]:
array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in array:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
array=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(array):
    print(x)

1
2
3
4
5
6
7
8


In [7]:
array=np.array([1,2,3])
for x in np.nditer(array,flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [8]:
array=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(array[:, ::2]):
    print(x)

1
3
5
7


In [9]:
array=np.array([0,1,2,3,4,5])
for index,x in np.ndenumerate(array):
    print(index,x)

(0,) 0
(1,) 1
(2,) 2
(3,) 3
(4,) 4
(5,) 5


In [10]:
arr=np.array([[1,2,3,4,5],[4,5,6,7,8,9]],dtype=object)
for index,x in np.ndenumerate(arr):
    print(index,x)

(0,) [1, 2, 3, 4, 5]
(1,) [4, 5, 6, 7, 8, 9]


In [11]:
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
new_array=np.concatenate((array1,array2))
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.array([[6,7,8],[9,10,11]])
new_array=np.concatenate((array1,array2),axis=1)
new_array

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10, 11]])

In [15]:
array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,0])
new_array=np.stack((array1,array2),axis=1)
new_array

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [16]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
x=np.hstack((array1,array2))
x

array([1, 2, 3, 4, 5, 6])

In [17]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
x=np.vstack((array1,array2))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
x=np.dstack((array1,array2))
x

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [20]:
array=np.arange(0,10,2)
print(array)
n_p=np.array_split(array,3)
print(n_p)

[0 2 4 6 8]
[array([0, 2]), array([4, 6]), array([8])]


In [21]:
array=np.arange(0,50,5)
print(array)
n_p=np.array_split(array,4)
n_p

[ 0  5 10 15 20 25 30 35 40 45]


[array([ 0,  5, 10]), array([15, 20, 25]), array([30, 35]), array([40, 45])]

In [22]:
arr=np.array([1,2,2,5,2,7,2,4,1,2],dtype=int)
x=np.where(arr==2)
x

(array([1, 2, 4, 6, 9], dtype=int64),)

In [23]:
arr=np.arange(0,10)
new=np.where(arr%2==1)
new

(array([1, 3, 5, 7, 9], dtype=int64),)

In [24]:
arr=np.array(["A","B","C","D","E","F","G","H","I","J","K","L","M","N"],dtype=object)
new=np.where(arr==(["H"]))
new

(array([7], dtype=int64),)

In [25]:
arr=np.array(["A","B","C","D","E","F","G","H","I","J","K","L","M","N"],dtype=object)
new=np.searchsorted(arr,"E")
new

4

In [26]:
arr=np.array(["A","B","C","D","E","F","G","H","I","J","K","L","M","N"],dtype=object)
new=np.searchsorted(arr,"E", side='right')
new

5

In [27]:
arr=np.array([0,25,8,44,6,888,664,2615,3,4,5])
new_arr=np.sort(arr)
new_arr

array([   0,    3,    4,    5,    6,    8,   25,   44,  664,  888, 2615])

In [28]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [29]:
arr = np.array([True, False, True])
print(np.sort(arr))

[False  True  True]


In [30]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
